### ISSUE TITLE
About APs,APm,APL

### ISSUE THREAD

**Issue by LEE-JAEHA** [zhenghao977/FCOS-PyTorch-37.2AP#10]
Hello. I'm looking at your code and the performance you posted on Readme is as below.

Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.207
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.410
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.495

But when I actually turned it around, the performance isn't that good, is the parameter setting different from the one posted on GitHub?

And what kind of backbone network is the performance that comes from?

And one more  could  you tell me the difference from the official fcos code?

Thank you.

**Comment by zhenghao977** [comment]
@LEE-JAEHA Hello, can you provide more training details?

**Comment by LEE-JAEHA** [comment]
@zhenghao977 

Thank you for your answer.
In the case of training detail, I did exactly what you wrote on config.py, and used the backbone that is pre-trained resnet101 on ImageNet


In the author's paper  uses resnet 50 and the Aps Aptm APl came out with 19.7 39.7 48.8,
 but your code  performance was not get that result.

Can I know your training detail?

-----------------




class DefaultConfig():
    #backbone
    pretrained=True
    freeze_stage_1=True
    freeze_bn=True

    #fpn
    fpn_out_channels=256
    use_p5=True
    
    #head
    class_num=80
    use_GN_head=True
    prior=0.01
    add_centerness=True
    cnt_on_reg=True

    #training
    strides=[8,16,32,64,128]
    limit_range=[[-1,64],[64,128],[128,256],[256,512],[512,999999]]

    #inference
    score_threshold=0.05
    nms_iou_threshold=0.6
    max_detection_boxes_num=1000

**Comment by zhenghao977** [comment]
@LEE-JAEHA OK, I see.  I trained coco2017 on 4 Tesla-V100 .batch_size is 16, init lr=1e-2 , total epoch is 24.  Other settings are same as config.py.

**Comment by LEE-JAEHA** [comment]
@zhenghao977  
Could yo tell me the backbone network?

**Comment by zhenghao977** [comment]
@LEE-JAEHA All models are resnet50

**Comment by LEE-JAEHA** [comment]
@zhenghao977 
and could you tell me why you set the img size with [800,1333]??
I don't get that much performance even if I train, is there any effect on the image size?

Thank you so much

**Comment by zhenghao977** [comment]
@LEE-JAEHA img size has a big effect, if you use low resolution, the results must be worse. You can refer to the original paper for this resolution(800,1333).
