### ISSUE TITLE
resnet50的权重能提供一下么

### ISSUE THREAD

**Issue by SSJIACV** [zhenghao977/FCOS-PyTorch-37.2AP#11]
如题：resnet50.pth能给个百度云链接么，谢谢了

**Comment by SSJIACV** [comment]
不用了   我下载了

**Comment by sparshgarg23** [comment]
I am facing issues with the resnet model,when I use pretrained resnet50 model,I end up recieiving the error missing fc.weight and fc,bias ,how did you go about solving it

**Comment by zhenghao977** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by EmeryBAI** [comment]
> 不用了 我下载了

请问在哪里下载？
