### ISSUE TITLE
可视化结果很差

### ISSUE THREAD

**Issue by wushilian** [zhenghao977/FCOS-PyTorch-37.2AP#4]
用提供的coco权重，运行detect.py去测试，发现结果很差
![Uploading 002295.jpg…]()
![004050](https://user-images.githubusercontent.com/13150055/93446691-14a89780-f904-11ea-9f7d-9b081ada346c.jpg)
![009204](https://user-images.githubusercontent.com/13150055/93446737-1ffbc300-f904-11ea-8905-1b631a504924.jpg)

**Comment by ChingHo97** [comment]
detect.py是针对voc可视化的，对于上述情况，确保model load正确，以及可视化的时候提高confidence。

**Comment by wushilian** [comment]
@ChingHo97 把voc改成coco了，这不是置信度的问题，可以看到图中的框confidence都很低。用这个代码在coco上训练，detect的结果也很差
