### ISSUE TITLE
Can you give me some advice

### ISSUE THREAD

**Issue by caiduoduo12138** [zhenghao977/FCOS-PyTorch-37.2AP#5]
You did a great job. When I calculate the mAP on COCO Dataset, it seems to be lower then you do. Can you give me some advice about the hyper-parameter,such as batch-szie, lr and so on. I have two GPUS(2080ti). Thanks you.

**Comment by zhenghao977** [comment]
I use 4 Tesla V100， and batch-size is 16, lr is 0.01 , you can see readme
