### ISSUE TITLE
你好 我改了原文网络 用这个数据集 map达到了0.897 请问算是很大的提升吗？

### ISSUE THREAD

**Issue by Dapeng960208** [zhenghao977/FCOS-PyTorch-37.2AP#6]
ap for aeroplane is 0.9380567591582296
ap for bicycle is 0.9023500291689587
ap for bird is 0.9437036916098254
ap for boat is 0.8359743513566958
ap for bottle is 0.8032454349459615
ap for bus is 0.9342764262934609
ap for car is 0.8585514817842739
ap for cat is 0.9925084130423817
ap for chair is 0.7292643574182338
ap for cow is 0.9375359094086273
ap for diningtable is 0.6475493395647764
ap for dog is 0.9876765272418895
ap for horse is 0.9666172732613725
ap for motorbike is 0.9114585891450979
ap for person is 0.8979392369795223
ap for pottedplant is 0.7230285310500533
ap for sheep is 0.902755284427134
ap for sofa is 0.8116387496591522
ap for train is 0.9630694195465596
ap for tvmonitor is 0.8966949641025459
mAP=====>0.879

**Comment by Linamiao-1998** [comment]
hello, I have some questions, if you have time ,can you give me some help ,  please  @Dapeng960208

**Comment by Linamiao-1998** [comment]
my qq is 3417592870 @Dapeng960208

**Comment by Dapeng960208** [comment]
sorry，i use the voc2012 val.txt to do it ,so it make no sense

**Comment by Dapeng960208** [comment]
[https://colab.research.google.com/drive/1xpS6xO-v4WAgwasklFodCy_AjDJbXSsw#scrollTo=SFvewUyuNNRZ](url)
