### ISSUE TITLE
感觉莫名训练COCO的时候卡住了，新手不太懂原因

### ISSUE THREAD

**Issue by Jack-Willian** [zhenghao977/FCOS-PyTorch-37.2AP#7]
![Snipaste_2020-11-08_11-21-51](https://user-images.githubusercontent.com/53688829/98456139-ab7f2b00-21b4-11eb-8ad6-0f5cc806bd46.png)

**Comment by Jack-Willian** [comment]
显示完
loading annotations into memory...
Done (t=16.55s)
creating index...
index created!
INFO====>check annos, filtering invalid data......
INFO===>success frozen BN
INFO===>success frozen backbone stage1
就一直僵着

**Comment by Sunsherly** [comment]
我也有这个问题，卡在了for epoch_step, data in enumerate(train_loader):

**Comment by Sunsherly** [comment]
我也不清楚具体原因，好像是因为数据集路径的格式问题，之前我用的的相对路径，把相对路径换成绝对路径就可以跑起来了。

**Comment by zhenghao977** [comment]
@Jack-Willian 可以检查一下是不是设置的num_worker过大，可以先把worker改成0测试一下。
