### ISSUE TITLE
voc dataset

### ISSUE THREAD

**Issue by Linamiao-1998** [zhenghao977/FCOS-PyTorch-37.2AP#8]
您好，博主，请问使用voc数据集时，path指的是所有数据的路径嘛， 数据集的各个文件夹的层次关系是什么，即数据集的格式是什么样子的，希望您有空可以指点一下我

**Comment by zhenghao977** [comment]
@Linamiao-1998 参考里面pascal VOC https://github.com/YuwenXiong/py-R-FCN
