### ISSUE TITLE
训练结束后模型权重的保存

### ISSUE THREAD

**Issue by Linamiao-1998** [zhenghao977/FCOS-PyTorch-37.2AP#9]
您好，博主，我的训练结束后模型权重文件并没有保存到指定文件夹中，这时如何修改呀。
torch.save(model.state_dict(),"pytorchDebug/FCOS-PyTorch-37.2AP/output/model_{}.pth".format(epoch + 1))
这句话感觉没有问题呀

**Comment by zhenghao977** [comment]
检查一下这个文件夹是否存在吧
